runner:
  total_steps: 50000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 100
  eval_step: 1000
  save_step: 1000
  max_keep: 1
  observation: [dev, acc]
  eval_dataloaders:
    - dev
  
optimizer:
  name: ChildnetAdamW
  reserve_p: [0.1, 0.01, 0.001]
  lr: 5.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 1400

downstream_expert:
  datarc:
    speech_commands_root: /home/yoos/Documents/data/speech_commands_v0.01
    speech_commands_test_root: /home/yoos/Documents/data/speech_commands_test_set_v0.01
    num_workers: 8
    batch_size: 32

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling
